# Generated by Django 2.0.2 on 2020-03-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('real_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('wechat', models.CharField(max_length=30)),
                ('dept', models.CharField(choices=[('11', '运维部'), ('12', '开发部'), ('12', '运营部'), ('12', '产品部')], max_length=2)),
                ('role', models.CharField(choices=[('1', '工程师'), ('1', '主管'), ('1', '总监')], max_length=2)),
                ('status', models.CharField(choices=[('1', '正常'), ('2', '冻结'), ('3', '注销')], max_length=1)),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeItem',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FieldItem',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('field_item', models.CharField(max_length=10)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interest_item', models.CharField(max_length=10)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolItem',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=8)),
                ('is_211', models.BooleanField()),
                ('is_985', models.BooleanField()),
                ('hold_type', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=3)),
                ('belong', models.CharField(max_length=20)),
                ('edu_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyItem',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('specialty_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('auth', models.CharField(choices=[('01', '用户名'), ('02', '手机'), ('03', '邮箱')], max_length=2)),
                ('identifier', models.CharField(max_length=50)),
                ('credential', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=13)),
                ('image_path', models.ImageField(upload_to='avatar\\')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('question1', models.CharField(max_length=30)),
                ('answer1', models.CharField(max_length=30)),
                ('question2', models.CharField(max_length=30)),
                ('answer2', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('1', '正常'), ('2', '冻结'), ('3', '注销')], max_length=1)),
                ('identity', models.CharField(choices=[('1', '在校生'), ('2', '毕业生'), ('3', '老师')], max_length=1)),
                ('qualification', models.CharField(choices=[('11', '专科'), ('12', '本科'), ('13', '硕士'), ('14', '博士'), ('15', '博士后'), ('21', '讲师'), ('22', '副教授'), ('23', '教授')], max_length=2)),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.CollegeItem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.SchoolItem')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.SpecialtyItem')),
            ],
        ),
        migrations.AddField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.UserInfo'),
        ),
        migrations.AddField(
            model_name='interestitem',
            name='interest_to_user',
            field=models.ManyToManyField(to='userzone.UserInfo'),
        ),
        migrations.AddField(
            model_name='fielditem',
            name='field_to_user',
            field=models.ManyToManyField(to='userzone.UserInfo'),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.SchoolItem'),
        ),
    ]
