# Generated by Django 2.0.2 on 2020-03-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('userzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowse',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('browse_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attitude', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_content', models.CharField(max_length=50)),
                ('search_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.UserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='role',
            field=models.CharField(choices=[('11', '工程师'), ('12', '主管'), ('13', '总监')], max_length=2),
        ),
    ]
