# Generated by Django 2.0.2 on 2020-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzone', '0002_auto_20200306_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
