# Generated by Django 2.0.2 on 2020-03-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('like_num', models.IntegerField(default=0, null=True)),
                ('dislike_num', models.IntegerField(default=0, null=True)),
                ('comment_num', models.IntegerField(default=0, null=True)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('like_num', models.IntegerField(default=0, null=True)),
                ('dislike_num', models.IntegerField(default=0, null=True)),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzone.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('1', '显示'), ('2', '隐藏')], max_length=1)),
                ('priority', models.IntegerField(default=1, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('follower_num', models.IntegerField(default=0, null=True)),
                ('answer_num', models.IntegerField(default=0, null=True)),
                ('popularity', models.IntegerField(default=0, null=True)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=10)),
                ('tag_to_question', models.ManyToManyField(to='cms.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userzone.UserInfo'),
        ),
    ]
