# Generated by Django 2.0.2 on 2020-03-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200306_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='browse_view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
